blueprint:
  name: Controllo connessione modbus
  description: Automazione per il controllo della connessione modbus
  domain: automation
  source_url: https://github.com/gtias/HA_Blueprint/blueprint1.yaml
  author: Ias Energy Soc.Coop

mode: restart
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: /5
    condition:
  - condition: state
    entity_id: sensor.meter_activepower
    state: unknown
  - condition: state
    entity_id: sensor.meter_activepower
    state: unavailable

action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      title: Guasto connessione contatore
      message: Il contatore sembra non essere disponibile, se il problema persiste
        contattare il servizio tecnico
